
title: Sergi Rodriguez
email: sergi86@gmail.com
description: >
  Web Developer specialized in PHP, MySQL, HTML5, CSS3 and Javascript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

permalink: pretty

social:
    linkedin: http://es.linkedin.com/in/sergirodriguez86
    github: https://github.com/rod86

# Build settings
source: _src
destination: _build
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - _assets
  - gulpfile.js
  - .DS_Store

# do not delete files in _site folder
keep_files:
  - js
  - css
  - fonts

# Frontmatter defaults
defaults:
    - scope:
        path: ""
        type: "pages"
      values:
          layout: "page"
          # layout two_columns_image
          image: ""

    - scope:
        path: ""
        type: "projects"
      values:
          layout: "project"

# Collections
collections:
    projects:
        output: true
        collections_dir: _projects
        permalink: /portfolio/project/:title/
        layout: project

# Portfolio config
portfolio:
    images_dir: /assets/images/portfolio/
